meta_product_name: "Gervais Paris"
meta_title: "Gervais Image Communication "
meta_description: "Réservez un studio près de chez vous : trouvez un studio selon vos critères, vérifiez les disponibilités, réservez en ligne."
meta_image: "logo_gic.png" # should exist in `app/assets/images/`
