meta_product_name: "Geoffrey Gervais Image Communication Paris"
meta_title: "Geoffrey Gervais Image Communication"
meta_description: "Geoffrey Gervais Image Communication Paris"
meta_image: "logo_gic.png" # should exist in `app/assets/images/`
